import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { generateSimpleDataObjectsFiles } from "../src/generator.js";

describe("generateSimpleDataObjectsFiles", () => {
  it("generates an empty BaseData class with the stable Data suffix", () => {
    const files = generateSimpleDataObjectsFiles({
      modules: [
        {
          path: "health/health.skir",
          records: [
            {
              kind: "struct",
              name: "HealthRequest",
              fields: [],
            },
          ],
        },
      ],
    });
    const struct = files.find((file) => file.path === "Health/HealthRequestData.php");

    expect(struct?.code).toBe([
      "<?php",
      "",
      "declare(strict_types=1);",
      "",
      "/**",
      " * +------------------------------------------------------------+",
      " * |                        DO NOT EDIT                         |",
      " * |      Generated by Skir. Changes will be overwritten.       |",
      " * +------------------------------------------------------------+",
      " */",
      "",
      "namespace Skir\\Health;",
      "",
      "use Skir\\Runtime\\DenseJson;",
      "use Skir\\Runtime\\Field;",
      "use Skir\\Runtime\\Type;",
      "use StdOut\\SimpleDataObjects\\BaseData;",
      "",
      "final class HealthRequestData extends BaseData",
      "{",
      "    public static function skirType(): Type",
      "    {",
      "        return Type::struct([]);",
      "    }",
      "",
      "    /** @param array<string, mixed> $data */",
      "    public static function makeFromSkirPayload(array $data): self",
      "    {",
      "        self::validate($data);",
      "",
      "        $payload = [];",
      "",
      "        return self::from($payload);",
      "    }",
      "",
      "    public static function fromSkir(string $json): HealthRequestData",
      "    {",
      "        $data = DenseJson::fromJson(self::skirType(), $json);",
      "",
      "        return self::makeFromSkirPayload($data);",
      "    }",
      "",
      "    /** @return array<string, mixed> */",
      "    public function toSkirArray(): array",
      "    {",
      "        return [];",
      "    }",
      "",
      "    /** @return array<int, mixed> */",
      "    public function toSkir(): array",
      "    {",
      "        return DenseJson::encode(self::skirType(), $this->toSkirArray());",
      "    }",
      "",
      "    public function toSkirJson(): string",
      "    {",
      "        return DenseJson::toJson(self::skirType(), $this->toSkirArray());",
      "    }",
      "}",
      "",
    ].join("\n"));
    expect(struct?.code).not.toContain("__construct");
  });

  it("generates mapped readonly fields, typed collections, validation, and Skir conversions", () => {
    const files = generateSimpleDataObjectsFiles({
      config: {
        namespace: "App\\Skir",
        validation: {
          "users.skir": {
            User: {
              user_id: ["min:1", "custom_user_id"],
            },
          },
        },
      },
      modules: [
        {
          path: "users.skir",
          records: [
            {
              kind: "struct",
              key: "address-key",
              name: "Address",
              fields: [
                { kind: "field", name: "city", number: 0, type: { kind: "string" } },
              ],
            },
            {
              kind: "struct",
              key: "user-key",
              name: "User",
              fields: [
                { kind: "field", name: "user_id", number: 0, type: { kind: "int32" } },
                { kind: "removed", number: 1 },
                { kind: "field", name: "address", number: 2, type: { kind: "record", key: "address-key", name: "Address" } },
                { kind: "field", name: "previous_addresses", number: 3, type: { kind: "array", item: { kind: "record", key: "address-key", name: "Address" } } },
                { kind: "field", name: "optional_addresses", number: 4, type: { kind: "optional", other: { kind: "array", item: { kind: "record", key: "address-key", name: "Address" } } } },
                { kind: "field", name: "nullable_addresses", number: 5, type: { kind: "array", item: { kind: "optional", other: { kind: "record", key: "address-key", name: "Address" } } } },
                { kind: "field", name: "nested_addresses", number: 6, type: { kind: "array", item: { kind: "array", item: { kind: "record", key: "address-key", name: "Address" } } } },
                { kind: "field", name: "labels", number: 7, type: { kind: "array", item: { kind: "string" } } },
                { kind: "field", name: "nickname", number: 8, type: { kind: "optional", other: { kind: "string" } } },
                { kind: "field", name: "large_id", number: 9, type: { kind: "int64" } },
                { kind: "field", name: "status", number: 10, type: { kind: "record", key: "status-key", name: "SubscriptionStatus", recordType: "enum" } },
              ],
            },
            {
              recordType: "enum",
              key: "status-key",
              name: "SubscriptionStatus",
              fields: [
                { kind: "field", name: "free", number: 1 },
                { kind: "field", name: "premium_since", number: 2, type: { kind: "timestamp" } },
              ],
            },
          ],
        },
      ],
    });
    const user = files.find((file) => file.path === "UserData.php")?.code ?? "";
    const status = files.find((file) => file.path === "SubscriptionStatusData.php")?.code ?? "";

    expect(user).toContain("use StdOut\\SimpleDataObjects\\Attributes\\DataCollection;");
    expect(user).toContain("use StdOut\\SimpleDataObjects\\Attributes\\MapPropertyName;");
    expect(user).toContain("use StdOut\\SimpleDataObjects\\Attributes\\Rules;");
    expect(user).toContain("use StdOut\\SimpleDataObjects\\TypedDataCollection;");
    expect(user).toContain("#[MapPropertyName('user_id')]\n        #[Rules(['required', 'integer', 'min:1', 'custom_user_id'])]\n        public readonly int $userId,");
    expect(user).toContain("#[Rules(['required', 'array'])]\n        public readonly AddressData $address,");
    expect(user).toContain("#[DataCollection(AddressData::class)]\n        public readonly TypedDataCollection $previousAddresses,");
    expect(user).toContain("public readonly ?TypedDataCollection $optionalAddresses,");
    expect(user).toContain("public readonly array $nullableAddresses,");
    expect(user).toContain("public readonly array $nestedAddresses,");
    expect(user).toContain("public readonly array $labels,");
    expect(user).toContain("#[Rules(['nullable', 'string'])]");
    expect(user).toContain("#[Rules(['required'])]\n        public readonly int|string $largeId,");
    expect(user).toContain("public readonly SubscriptionStatusData $status,");
    expect(user).toContain("public static function skirType(): Type");
    expect(user).toContain("Field::removed(1)");
    expect(user).toContain("public static function makeFromSkirPayload(array $data): self");
    expect(user.indexOf("self::validate($data);")).toBeLessThan(
      user.indexOf("AddressData::makeFromSkirPayload($data['address'])"),
    );
    expect(user).toContain("'previous_addresses' => array_map(");
    expect(user).toContain("AddressData::makeFromSkirPayload($item)");
    expect(user).toContain("'nickname' => $data['nickname'] ?? null,");
    expect(user).toContain("($data['optional_addresses'] ?? null) === null ? null : array_map(");
    expect(user).toContain("'status' => SubscriptionStatusData::fromSkirValue($data['status'])");
    expect(user).toContain("return self::from($payload);");
    expect(user).toContain("public static function fromSkir(string $json): UserData");
    expect(user).toContain("public function toSkirArray(): array");
    expect(user).toContain("$this->previousAddresses->all()");
    expect(user).toContain("public function toSkir(): array");
    expect(user).toContain("public function toSkirJson(): string");
    expect(status).toContain("final readonly class SubscriptionStatusData");
    expect(status).toContain("public static function premiumSince(int $value): self");
  });

  it("escapes attribute literals and resolves target import collisions", () => {
    const files = generateSimpleDataObjectsFiles({
      config: {
        validation: {
          "collision.skir": {
            Base: {
              quoted_value: ["regex:\\\\d+'s"],
            },
          },
        },
      },
      modules: [
        {
          path: "collision.skir",
          records: [
            {
              kind: "struct",
              name: "Base",
              fields: [
                { kind: "field", name: "quoted_value", number: 0, type: { kind: "string" } },
              ],
            },
          ],
        },
      ],
    });
    const source = files.find((file) => file.path === "BaseData.php")?.code ?? "";

    expect(source).toContain("use StdOut\\SimpleDataObjects\\BaseData as SimpleDataObjectsBaseData;");
    expect(source).toContain("final class BaseData extends SimpleDataObjectsBaseData");
    expect(source).toContain("#[MapPropertyName('quoted_value')]");
    expect(source).toContain("#[Rules(['required', 'string', 'regex:\\\\\\\\d+\\'s'])]");
  });

  it("rejects invalid validation selectors before rendering", () => {
    expect(() => generateSimpleDataObjectsFiles({
      config: {
        validation: {
          "users.skir": {
            User: {
              missing: ["required"],
            },
          },
        },
      },
      modules: [
        {
          path: "users.skir",
          records: [
            {
              kind: "struct",
              name: "User",
              fields: [
                { kind: "field", name: "name", number: 0, type: { kind: "string" } },
              ],
            },
          ],
        },
      ],
    })).toThrow('Unknown validation field "users.skir::User.missing".');
  });

  it("preserves LF, CR, and CRLF validation rule values with constant expressions", () => {
    const files = generateSimpleDataObjectsFiles({
      config: {
        validation: {
          "rules.skir": {
            ControlRules: {
              line_feed: ["line\nfeed"],
              carriage_return: ["carriage\rreturn"],
              both: ["both\r\nlines"],
            },
          },
        },
      },
      modules: [{
        path: "rules.skir",
        records: [{
          kind: "struct",
          name: "ControlRules",
          fields: [
            { kind: "field", name: "line_feed", number: 0, type: { kind: "string" } },
            { kind: "field", name: "carriage_return", number: 1, type: { kind: "string" } },
            { kind: "field", name: "both", number: 2, type: { kind: "string" } },
          ],
        }],
      }],
    });
    const source = files.find((file) => file.path === "ControlRulesData.php")?.code ?? "";

    expect(source).toContain("#[Rules(['required', 'string', 'line'.\"\\n\".'feed'])]");
    expect(source).toContain("#[Rules(['required', 'string', 'carriage'.\"\\r\".'return'])]");
    expect(source).toContain("#[Rules(['required', 'string', 'both'.\"\\r\".\"\\n\".'lines'])]");
  });

  it("converts complex wrapper enum payloads between wire and target representations", () => {
    const files = generateSimpleDataObjectsFiles({
      modules: [{
        path: "events.skir",
        records: [{
          kind: "struct",
          key: "address-key",
          name: "Address",
          fields: [
            { kind: "field", name: "city", number: 0, type: { kind: "string" } },
          ],
        }, {
          recordType: "enum",
          name: "AddressEvent",
          fields: [{
            kind: "field",
            name: "moved_to",
            number: 1,
            type: { kind: "record", key: "address-key", name: "Address" },
          }, {
            kind: "field",
            name: "visited",
            number: 2,
            type: { kind: "array", item: { kind: "record", key: "address-key", name: "Address" } },
          }, {
            kind: "field",
            name: "maybe_moved_to",
            number: 3,
            type: { kind: "optional", other: { kind: "record", key: "address-key", name: "Address" } },
          }, {
            kind: "field",
            name: "maybe_visited",
            number: 4,
            type: { kind: "optional", other: { kind: "array", item: { kind: "record", key: "address-key", name: "Address" } } },
          }, {
            kind: "field",
            name: "routes",
            number: 5,
            type: { kind: "array", item: { kind: "array", item: { kind: "record", key: "address-key", name: "Address" } } },
          }],
        }],
      }],
    });
    const source = files.find((file) => file.path === "AddressEventData.php")?.code ?? "";

    expect(source).toContain("public static function movedTo(AddressData $value): self");
    expect(source).toContain("EnumValue::wrapper('moved_to', $value->toSkirArray())");
    expect(source).toContain("public static function visited(TypedDataCollection $value): self");
    expect(source).toContain("$value->all()");
    expect(source).toContain("'moved_to' => AddressData::makeFromSkirPayload($this->value->value),");
    expect(source).toContain("'visited' => TypedDataCollection::of(AddressData::class, array_map(");
    expect(source).toContain("'maybe_moved_to' => $this->value->value === null ? null : AddressData::makeFromSkirPayload($this->value->value),");
    expect(source).toContain("public static function maybeVisited(?TypedDataCollection $value): self");
    expect(source).toContain("'maybe_visited' => $this->value->value === null ? null : TypedDataCollection::of(AddressData::class, array_map(");
    expect(source).toContain("'routes' => array_map(");
  });

  it("generates the complete RPC surface and manifest with typed collection boundaries", () => {
    const files = generateSimpleDataObjectsFiles({
      config: {
        namespace: "App\\Skir",
      },
      modules: [{
        path: "rpc.skir",
        records: [{
          kind: "struct",
          key: "address-key",
          name: "Address",
          fields: [
            { kind: "field", name: "city", number: 0, type: { kind: "string" } },
          ],
        }, {
          recordType: "enum",
          name: "AddressStatus",
          fields: [
            { kind: "field", name: "unknown", number: 1 },
            { kind: "field", name: "known", number: 2, type: { kind: "record", key: "address-key", name: "Address" } },
          ],
        }],
        methods: [{
          kind: "method",
          name: "SyncAddresses",
          number: 42,
          requestType: { kind: "array", item: { kind: "record", key: "address-key", name: "Address" } },
          responseType: { kind: "optional", other: { kind: "array", item: { kind: "record", key: "address-key", name: "Address" } } },
        }, {
          kind: "method",
          name: "GetAddressStatus",
          number: 43,
          requestType: { kind: "record", key: "address-key", name: "Address" },
          responseType: { kind: "record", name: "AddressStatus", recordType: "enum" },
        }],
      }],
    });
    const client = files.find((file) => file.path === "SkirRpcClient.php")?.code ?? "";
    const procedures = files.find((file) => file.path === "SkirProcedures.php")?.code ?? "";
    const provider = files.find((file) => file.path === "SkirProcedureProvider.php")?.code ?? "";
    const abstractProcedures = files.find((file) => file.path === "AbstractSkirProcedures.php")?.code ?? "";
    const manifest = files.find((file) => file.path === "skir-server-manifest.json")?.code ?? "";

    expect(files.map((file) => file.path).sort()).toEqual([
      "AbstractSkirProcedures.php",
      "AddressData.php",
      "AddressStatusData.php",
      "SkirMethod.php",
      "SkirMethods.php",
      "SkirProcedureProvider.php",
      "SkirProcedures.php",
      "SkirRpcClient.php",
      "skir-server-manifest.json",
    ]);
    expect(client).toContain("public function syncAddresses(TypedDataCollection $request): ?TypedDataCollection");
    expect(client).toContain("$request->all()");
    expect(client).toContain("return $response === null ? null : TypedDataCollection::of(AddressData::class, array_map(");
    expect(procedures).toContain("public function syncAddresses(TypedDataCollection $request, SkirContext $context): ?TypedDataCollection;");
    expect(provider).toContain("TypedDataCollection::of(AddressData::class, array_map(");
    expect(provider).toContain("return $response === null ? null : array_map(");
    expect(provider).toContain("$response->all()");
    expect(abstractProcedures).toContain("abstract public function syncAddresses(TypedDataCollection $request, SkirContext $context): ?TypedDataCollection;");
    expect(JSON.parse(manifest)).toEqual({
      version: 1,
      generator: "skir-simple-data-objects-generator",
      modules: [{
        name: "_Root",
        methodEnum: "App\\Skir\\SkirMethod",
        methods: [{
          name: "SyncAddresses",
          enumCase: "SyncAddresses",
          phpMethod: "syncAddresses",
          requestType: "StdOut\\SimpleDataObjects\\TypedDataCollection",
          requestClass: null,
          responseType: "?StdOut\\SimpleDataObjects\\TypedDataCollection",
          responseClass: null,
        }, {
          name: "GetAddressStatus",
          enumCase: "GetAddressStatus",
          phpMethod: "getAddressStatus",
          requestType: "App\\Skir\\AddressData",
          requestClass: "App\\Skir\\AddressData",
          responseType: "App\\Skir\\AddressStatusData",
          responseClass: "App\\Skir\\AddressStatusData",
        }],
      }],
    });
  });

  it("keeps nested struct arrays as plain RPC arrays without target collection imports", () => {
    const files = generateSimpleDataObjectsFiles({
      modules: [{
        path: "nested-rpc.skir",
        records: [{
          kind: "struct",
          key: "item-key",
          name: "Item",
          fields: [],
        }],
        methods: [{
          kind: "method",
          name: "Nest",
          number: 45,
          requestType: {
            kind: "array",
            item: { kind: "array", item: { kind: "record", key: "item-key", name: "Item" } },
          },
          responseType: { kind: "array", item: { kind: "string" } },
        }],
      }],
    });
    const client = files.find((file) => file.path === "SkirRpcClient.php")?.code ?? "";

    expect(client).toContain("public function nest(array $request): array");
    expect(client).not.toContain("StdOut\\SimpleDataObjects\\TypedDataCollection");
  });

  it("preplans and aliases enum collection imports that collide with generated records", () => {
    const files = generateSimpleDataObjectsFiles({
      modules: [{
        path: "collision.skir",
        records: [{
          kind: "struct",
          key: "collection-key",
          name: "CollectionItem",
          phpClassName: "TypedDataCollection",
          fields: [
            { kind: "field", name: "name", number: 0, type: { kind: "string" } },
          ],
        }, {
          recordType: "enum",
          name: "CollectionEvent",
          fields: [{
            kind: "field",
            name: "collected",
            number: 1,
            type: {
              kind: "array",
              item: {
                kind: "record",
                key: "collection-key",
                name: "CollectionItem",
              },
            },
          }],
        }],
        methods: [{
          kind: "method",
          name: "Collect",
          number: 44,
          requestType: {
            kind: "array",
            item: { kind: "record", key: "collection-key", name: "CollectionItem" },
          },
          responseType: {
            kind: "array",
            item: { kind: "record", key: "collection-key", name: "CollectionItem" },
          },
        }],
      }],
    });
    const source = files.find((file) => file.path === "CollectionEventData.php")?.code ?? "";
    const client = files.find((file) => file.path === "SkirRpcClient.php")?.code ?? "";
    const provider = files.find((file) => file.path === "SkirProcedureProvider.php")?.code ?? "";
    const lintDirectory = mkdtempSync(join(tmpdir(), "skir-sdo-enum-import-"));
    const lintFile = join(lintDirectory, "CollectionEventData.php");

    expect(source).toContain(
      "use StdOut\\SimpleDataObjects\\TypedDataCollection as SimpleDataObjectsTypedDataCollection;",
    );
    expect(source).toContain(
      "public static function collected(SimpleDataObjectsTypedDataCollection $value): self",
    );
    expect(source).toContain(
      "SimpleDataObjectsTypedDataCollection::of(TypedDataCollection::class, array_map(",
    );
    expect(client).toContain(
      "use StdOut\\SimpleDataObjects\\TypedDataCollection as SimpleDataObjectsTypedDataCollection;",
    );
    expect(client).toContain(
      "public function collect(SimpleDataObjectsTypedDataCollection $request): SimpleDataObjectsTypedDataCollection",
    );
    expect(client).toContain(
      "SimpleDataObjectsTypedDataCollection::of(TypedDataCollection::class, array_map(",
    );
    expect(provider).toContain(
      "use StdOut\\SimpleDataObjects\\TypedDataCollection as SimpleDataObjectsTypedDataCollection;",
    );

    writeFileSync(lintFile, source);
    expect(() => execFileSync("php", ["-l", lintFile], { stdio: "pipe" })).not.toThrow();

    for (const [index, file] of files.filter((file) => file.path.endsWith(".php")).entries()) {
      const generatedLintFile = join(lintDirectory, `${index}.php`);

      writeFileSync(generatedLintFile, file.code);
      expect(() => execFileSync("php", ["-l", generatedLintFile], { stdio: "pipe" })).not.toThrow();
    }
  });
});
